<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="3.692" timestamp="2025-10-30T13:10:17.921348" hostname="DESKTOP-AITNV0T"><testcase classname="" name="tests.unit.test_dtype_utils" time="0.000"><error message="collection failure">ImportError while importing test module 'E:\github\bioactivity_data_acquisition\tests\unit\test_dtype_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\Fedor\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\unit\test_dtype_utils.py:5: in &lt;module&gt;
    from bioetl.utils.dtype import (
E   ModuleNotFoundError: No module named 'bioetl.utils.dtype'</error></testcase></testsuite></testsuites>